name: My First Workflow

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:   # 👈 enables manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check the Uptime time
        run: |
          sudo apt-get update
          sudo uptime

    steps:
      - name: Check the Worker and uname -2
        run: |
          sudo uname -r
          sudo w


